# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASPN_ios_Paris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASPN_ios_Paris

end
